services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3001"
      - "5555:5555"
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:prod"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped